### ISSUE TITLE
Not possible to compile cordova app when plugin is added

### ISSUE THREAD

**Issue by yurevichcv** [fabiogomiero/cordova-external-file-open#1]
[INF] 
[INF] -generate-cache-manifest:
[INF] 
[INF] -page:
[INF] 
[INF] -after-page:
[INF] 
[INF] native-package:
[INF] 
[INF] -build:
[INF] 
[INF] -after-build:
[INF] 
[INF] build:
[INF] 
[INF] app-build:

Generating config.xml from defaults for platform "ios"
Preparing ios project
Compiling app on platform "ios" via command "/Volumes/HDD/www/iCoordinatorMobile-cordova/platforms/ios/cordova/build" 
Error: An error occurred while building the ios project.2014-02-20 12:09:18.831 xcodebuild[49805:2007]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-3575/Xcode3Sources/XcodeIDE/Frameworks/DevToolsBase/pbxcore/SpecificationTypes/XCGccMakefileDependencies.m:78
Details:  Failed to load dependencies output contents from ``/Volumes/HDD/www/iCoordinatorMobile-cordova/platforms/ios/build/iCoordinatorMobile.build/Debug-iphoneos/iCoordinatorMobile.build/Objects-normal/armv7/FGExternalFileUtil.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “FGExternalFileUtil.d” couldn’t be opened because there is no such file." UserInfo=0x7fa70a4ae450 {NSFilePath=/Volumes/HDD/www/iCoordinatorMobile-cordova/platforms/ios/build/iCoordinatorMobile.build/Debug-iphoneos/iCoordinatorMobile.build/Objects-normal/armv7/FGExternalFileUtil.d, NSUnderlyingError=0x7fa70a48c590 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Volumes/HDD/www/iCoordinatorMobile-cordova/platforms/ios/build/iCoordinatorMobile.build/Debug-iphoneos/iCoordinatorMobile.build/Objects-normal/armv7/FGExternalFileUtil.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString ___strong, F) [F = <lambda at /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-3575/Xcode3Sources/XcodeIDE/Frameworks/DevToolsBase/pbxcore/SpecificationTypes/XCGccMakefileDependencies.m:168:73>]
Thread:   <NSThread: 0x7fa70a4a8c30>{name = (null), num = 9}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
*_ BUILD FAILED **

The following build commands failed:
    CompileC build/iCoordinatorMobile.build/Debug-iphoneos/iCoordinatorMobile.build/Objects-normal/armv7/FGExternalFileUtil.o iCoordinatorMobile/Plugins/com.fgomiero.cordova.externafileutil/FGExternalFileUtil.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
2014-02-20 12:09:20.159 xcodebuild[50013:7603]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-3575/Xcode3Sources/XcodeIDE/Frameworks/DevToolsBase/pbxcore/SpecificationTypes/XCGccMakefileDependencies.m:78
Details:  Failed to load dependencies output contents from ``/Volumes/HDD/www/iCoordinatorMobile-cordova/platforms/ios/build/iCoordinatorMobile.build/Debug-iphonesimulator/iCoordinatorMobile.build/Objects-normal/i386/FGExternalFileUtil.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “FGExternalFileUtil.d” couldn’t be opened because there is no such file." UserInfo=0x7fa55f5b58f0 {NSFilePath=/Volumes/HDD/www/iCoordinatorMobile-cordova/platforms/ios/build/iCoordinatorMobile.build/Debug-iphonesimulator/iCoordinatorMobile.build/Objects-normal/i386/FGExternalFileUtil.d, NSUnderlyingError=0x7fa55f5b59d0 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Volumes/HDD/www/iCoordinatorMobile-cordova/platforms/ios/build/iCoordinatorMobile.build/Debug-iphonesimulator/iCoordinatorMobile.build/Objects-normal/i386/FGExternalFileUtil.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString ___strong, F) [F = <lambda at /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-3575/Xcode3Sources/XcodeIDE/Frameworks/DevToolsBase/pbxcore/SpecificationTypes/XCGccMakefileDependencies.m:168:73>]
Thread:   <NSThread: 0x7fa55f5b4c00>{name = (null), num = 9}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
*_ BUILD FAILED **

The following build commands failed:
    CompileC build/iCoordinatorMobile.build/Debug-iphonesimulator/iCoordinatorMobile.build/Objects-normal/i386/FGExternalFileUtil.o iCoordinatorMobile/Plugins/com.fgomiero.cordova.externafileutil/FGExternalFileUtil.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

```
at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cordova/src/compile.js:65:22)
at ChildProcess.EventEmitter.emit (events.js:98:17)
at maybeClose (child_process.js:735:16)
at Socket.<anonymous> (child_process.js:948:11)
at Socket.EventEmitter.emit (events.js:95:17)
at Pipe.close (net.js:466:12)
```

**Comment by fabiogomiero** [comment]
Are you using XCode 5 and cordova >= 3.0.0?

**Comment by yurevichcv** [comment]
Yes, and I compile it using command line:
cordova plugin add https://github.com/critical/cordova-external-file-open.git
cordova build ios;

**Comment by yurevichcv** [comment]
I was able to fix this by setting path inside xcodeproj to files "FGExternalFileUtil.m" and "FGExternalFileUtil.h". I guess you should correct plugin config the way to install them automatically.
